### ISSUE TITLE
List akun twitter Politikus Indonesia

### ISSUE THREAD

**Issue by yogasukma** [agusk/akun#1]
Bukan punya saya, tapi ini lumayan banyak [https://twitter.com/bluthbiznezmode/lists/indonesian-politicians/members](https://twitter.com/bluthbiznezmode/lists/indonesian-politicians/members). walaupun yang verified twitter bisa di hitung jari, tapi sepertinya cukup 'legit'

**Comment by agusk** [comment]
sip. segera di follow up. Thanks info nya

**Comment by agusk** [comment]
ok, ditambahkan sebagian
